### ISSUE TITLE
Couldn't find previous build info

### ISSUE THREAD

**Issue by marvinhagemeister** [GoogleChromeLabs/travis-size-report#3]
We've recently adopted `travis-size-report` over at [preactjs](https://github.com/developit/preact) and are very excited about the ability to compare the size of PRs against `master` 👍

After playing a bit we've seemingly run into an issue where `travis-size-report` is unable to find the previous build info. We followed the README closely, but we're unsure if this is related to misconfiguration on our end or just a bug.

The complete message (slightly formatted for better readability):

```bash
$ sizereport --config
=== BUILD SIZES: [
  {"path":"./compat/dist/compat.js","size":4970,"gzipSize":2076},
  {"path":"./compat/dist/compat.module.js","size":4698,"gzipSize":2062},
  {"path":"./compat/dist/compat.umd.js","size":5059,"gzipSize":2129},  
  {"path":"./debug/dist/debug.js","size":10086,"gzipSize":3853},
  {"path":"./debug/dist/debug.module.js","size":9911,"gzipSize":3831},
  {"path":"./debug/dist/debug.umd.js","size":10250,"gzipSize":3908},
  {"path":"./dist/preact.js","size":9564,"gzipSize":3861},
  {"path":"./dist/preact.module.js","size":9529,"gzipSize":3891},
  {"path":"./dist/preact.umd.js","size":9664,"gzipSize":3933},
  {"path":"./hooks/dist/hooks.js","size":2036,"gzipSize":855},
  {"path":"./hooks/dist/hooks.module.js","size":1942,"gzipSize":877},
  {"path":"./hooks/dist/hooks.umd.js","size":2177,"gzipSize":919}
]
Build change report:
  Couldn't find previous build info
```

Link to full logs: https://travis-ci.org/developit/preact/builds/535054061#L1609

**Comment by jakearchibald** [comment]
I'll dig into this a bit more, but here's some early thoughts:

I can't find a `master` build that contains size info. Eg https://travis-ci.org/developit/preact/builds/533536070 (and all master builds since then) have failed for an unrelated reason.

**Comment by marvinhagemeister** [comment]
Ohh that's a good pointer! Our master build has been failing for a while due to an issue with the saucelabs macos vm. I'll close this as it's very likely that this is the cause.

Thank you so much for the quick response 👍💯

**Comment by jakearchibald** [comment]
No problem! Hope preact finds it useful. Let me know if there's anything you'd like to change/add.
